name: sports_booking_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  syncfusion_flutter_datepicker: ^20.1.59
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.1
  google_fonts: ^3.0.1
  flutter_spinkit: ^5.1.0

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
